### ISSUE TITLE
[FEATURE][CS][INQUIRY] 1:1문의 작성페이지

### ISSUE THREAD

**Issue by Bini0104** [S-O-O-P/S-O-O-P-React#11]
## 💼 어떤 기능인가요?
> 1:1문의 작성페이지

![image](https://github.com/S-O-O-P/S-O-O-P-React/assets/157683303/00ae49b1-5d89-4456-b045-a2eb3609f8ea)

**Comment by LEEMINKUK** [comment]
아주 좋습니다 굿굿
