### ISSUE TITLE
[FEATURE][CULTUREINFO][MAIN] 전시/공연 정보 메인 페이지 레이아웃

### ISSUE THREAD

**Issue by shubiduba1212** [S-O-O-P/S-O-O-P-React#12]
## 💼 어떤 기능인가요?
[FEATURE][CULTUREINFO][MAIN] 전시/공연 정보 메인 페이지 레이아웃

## ✅ 작업 상세 내용
- [x] HOT 전시/공연 정보
- [x] 얼리버드 정보
- [x] 전시/공연 정보 둘러보기
     -  카드 형식
     -  테이블 형식  
- [x] 상세페이지 연결
      

## 📚 참고할만한 자료(선택)
![image](https://github.com/S-O-O-P/S-O-O-P-React/assets/73331620/81e5ff4d-d718-4993-99d0-3592878d6f82)
![image](https://github.com/S-O-O-P/S-O-O-P-React/assets/73331620/2bc5fd7c-6c16-4866-af14-bbf8f9e53a3e)

**Comment by LEEMINKUK** [comment]
많이 하셨네요 파이팅 입니다

**Comment by LEEMINKUK** [comment]
고생 하셨습니다.
