### ISSUE TITLE
[DEVELOP] 1:1문의 무한 루프 에러

### ISSUE THREAD

**Issue by LEEMINKUK** [S-O-O-P/S-O-O-P-React#153]
##  💼 어떤 기능인가요?
> [DEVELOP] 1:1문의 무한 루프 에러

## ✅ 작업 상세 내용
- [ ] 관리자 페이지 답변작성후 무한루프 에러. ( UseEffect 내부 )

## 🐝 결과

![image](https://github.com/user-attachments/assets/6a397a13-15b7-4541-ba0d-2d3562de8c2b)

**Comment by neogoolboss** [comment]
useEffect 내부에 관리부분 state 상태 중복입니다.

해당 useEffect 맨 아래 , [ ] 배열에서 마지막 내용 지우고 실행해보세요.

그리고 여긴 클라이언트입니다.
