### ISSUE TITLE
[FEATURE][CS][MAIN] 고객센터 메인페이지

### ISSUE THREAD

**Issue by Bini0104** [S-O-O-P/S-O-O-P-React#2]
## 💼 어떤 기능인가요?
> 고객센터 메인 페이지

![image](https://github.com/S-O-O-P/S-O-O-P-React/assets/157683303/a2e7da28-8896-44a5-92d2-5e4d1bd9e4ce)

**Comment by neogoolboss** [comment]
이슈 제목 [FEATURE][CS][MAIN] 설명 으로 변경해주세요.
우측에 프로젝트 연결해놨습니다. 다음부터는 프로젝트에도 연결해주세요.

**Comment by LEEMINKUK** [comment]
고생 하셨습니다
