### ISSUE TITLE
[FEATURE][CS][FAQ] 자주 묻는 질문 페이지 수정

### ISSUE THREAD

**Issue by Bini0104** [S-O-O-P/S-O-O-P-React#29]
## ✅ 작업 상세 내용
- [x] 검색 기능
- [x] 페이지네이션+토글 수정

![image](https://github.com/S-O-O-P/S-O-O-P-React/assets/157683303/de4d8a31-f9ba-422c-a500-a45ab9a6f5cf)
> 다음 페이지 이동 시 토글  true 값이 남아있음

**Comment by neogoolboss** [comment]
const toggleFAQ = (index) => {
        setIsOpen((prev) =>
            prev.map((item, i) => (i === index ? !item : item))
        );
    };
    
    으로 되어 있는 부분에서 뒤에 item을 false로 바꿔보세요

클릭한 해당 인덱스가 아닐 경우에도 item(내용)을 보여주는걸로 되어있는데 false로 처리하면 닫힘 상태로 나타납니다.
페이지 네이션 이동 시에도 인덱스가 달라지기 때문에 닫힙니다.

prev.map((item, i) => (i === index ? !item : false)) <--이렇게 해보세요
