### ISSUE TITLE
[FEATURE][HONEY][MAIN] 허니팟 메인페이지 구성 FE

### ISSUE THREAD

**Issue by cwul94** [S-O-O-P/S-O-O-P-React#3]
## 💼 어떤 기능인가요?
>[FEATURE][HONEY][MAIN] 허니팟 메인페이지 구성 - FE

## ✅ 작업 상세 내용
- [x] CRA 및 기본 페이지 라우팅 작업
- [x] 카테고리별 data 매핑&바인딩 작업 : React hooks 설계
- [x] 페이지네이션
- [x] 제목 검색
- [x] 정렬 기준 검색 : 일정별(date자료형 포맷 미확정 / filter()함수 내 includes()함수 미작동 이슈) & 지역별(filter()함수 내 includes()함수 미작동 이슈) 기능 미구현
- [x] 일정별 목록 기능 Modal 구현

## 1. 메인 뷰 ver.1 - 240619 
![pull_request_ver2](https://github.com/S-O-O-P/S-O-O-P-React/assets/90615404/6d94b89c-76ca-41dd-81d3-817a786f01a4)

## 2. 메인 뷰 ver.2 - 240623

- 투데이
![0623메인뷰_투데이](https://github.com/S-O-O-P/S-O-O-P-React/assets/90615404/f9e6487e-25c9-40aa-a3cd-10b03a62e93e)

- 장르별
![0623메인뷰_장르별](https://github.com/S-O-O-P/S-O-O-P-React/assets/90615404/db1649a8-ec75-4b19-ad86-47fd02d4730b)

- 일정별
![일정조회모달](https://github.com/S-O-O-P/S-O-O-P-React/assets/90615404/463e1832-a574-4327-bc60-87f71bca52fe)

## 3. 메인 뷰 ver.3 - 240623

- 댓글 개수 & 지역 정보 추가 및 css 조정
![메인뷰_추가](https://github.com/S-O-O-P/S-O-O-P-React/assets/90615404/7a3acd7c-a318-41fd-8e26-f376354d13a3)

## 관련 이슈
1. 날짜 관련 state는 임의 문자열 데이터로 사용하기 때문에 실제 사용될 데이터인 date 자료형과 연관지어 로직이 구현되어야하기때문에 날짜 포맷이 정해지지 않은 현 시점에서 구현하는건 적절하지 않다고 판단했습니다. 따라서 실제 데이터와 바인딩시 자료형 바인딩에 문제없는 state만 연결되어있는 상태입니다.
2. 따라서 일정 관련 기능은 미구현상태입니다. BE작업시 추가하는게 적절하다고 판단하고있습니다.
3. 정렬&검색 기능은 useEffect 함수로 select(=최신순,지역별,모집중,모집완료)/searchVal(:state) dom-tree update시 허니팟 목록 list(:state)를 mount할 때, filter()함수 내에 includes() 함수를 사용해 전달인자가 데이터에 포함되어 있는 데이터를 boolean 자료형으로 반환해 true인 값의 목록으로 list를 update하게 됩니다. 또 filter()함수 또한 boolean 형으로 반환받는데 이때 &&(and) 연산자를 사용하는 부분에 있어 오류가 있어 5가지(select(=최신순,지역별,모집중,모집완료)/searchVal(:state))를 비교해야 함에도 두가지(select/searchVall)만 filter() 되어 출력되고 있습니다. 
5. 현재 파악중인 이슈로는, filter()함수 내에 비교해야하는값이 너무 많아 react dom mount/update차원에서 혼동이 있어 비교할수 있는 최대값이 정해져 있을까? 라는 접근을 하고 있습니다.
6. 해당 이슈는 BE 구현 기간에 좀 더 다뤄볼 예정입니다.
7. 임시 데이터
![임시데이터](https://github.com/S-O-O-P/S-O-O-P-React/assets/90615404/81e2dd9b-f9d9-4ccf-b580-6f80446d68f2)

**Comment by LEEMINKUK** [comment]
파이팅 입니다
