### ISSUE TITLE
[FEATURE][MAIN]MAIN 페이지 레이아웃

### ISSUE THREAD

**Issue by shubiduba1212** [S-O-O-P/S-O-O-P-React#33]
## 💼 어떤 기능인가요?
[FEATURE][MAIN]MAIN 페이지의 레이아웃 작업입니다.

## ✅ 작업 상세 내용
- [x] MAIN 페이지 레이아웃
- [x] 윈도우 스크롤시 HEADER 색상 변화  
- [x] 슬라이드 기능 적용
- [x] TOP 버튼
- [x] 상세페이지 연결
- [x] 더보기 버튼 클릭시 공연/전시 페이지 연결

### 전체 화면(스크롤 전)
![screencapture-localhost-3000-main-2024-06-23-03_10_08](https://github.com/S-O-O-P/S-O-O-P-React/assets/73331620/6bb4ad78-5d9f-4729-87af-f478825fe995)

### 화면 스크롤시
![image](https://github.com/S-O-O-P/S-O-O-P-React/assets/73331620/94b87841-c552-444d-b0f1-477c25110c54)

**Comment by LEEMINKUK** [comment]
고생 하셨습니다.
