### ISSUE TITLE
[FEATURE][CULTUREINFO][DETAIL] 공연/전시 정보 상세 페이지 레이아웃

### ISSUE THREAD

**Issue by shubiduba1212** [S-O-O-P/S-O-O-P-React#34]
## 💼 어떤 기능인가요?
[FEATURE][CULTUREINFO][DETAIL] 공연/전시 정보 상세 페이지 레이아웃 작업입니다.

## ✅ 작업 상세 내용
- [x] 공연/전시 정보 상세 페이지 레이아웃
- [x] 하단 탭 버튼 기능

**Comment by LEEMINKUK** [comment]
기능 구현 잘된 것 확인 했습니다
