### ISSUE TITLE
[FEATURE][CS][FAQ]자주 묻는 질문 페이지

### ISSUE THREAD

**Issue by Bini0104** [S-O-O-P/S-O-O-P-React#4]
## 💼 어떤 기능인가요?
> 자주 묻는 질문 페이지
--- 
![image](https://github.com/S-O-O-P/S-O-O-P-React/assets/157683303/bad95505-ab0b-4c83-8c6a-850d4c38c4d7)

**Comment by LEEMINKUK** [comment]
피그마 그대로 구현 되었네요 고생 하셨습니다,
