### ISSUE TITLE
[FEATURE] HEADER & FOOTER console에러 해결 및 수정한 사항 정리

### ISSUE THREAD

**Issue by shubiduba1212** [S-O-O-P/S-O-O-P-React#52]
##상세 내용
> [Branch][본인 브랜치 이름]

## 작업 상세 내용
- [x] FOOTER > Footer.js - Link 태그 내 a태그 사용으로 태그 중복 에러
![footer_a_code](https://github.com/S-O-O-P/S-O-O-P-React/assets/73331620/b9673b91-b663-4b87-8f8e-789221399a3e)
![footer_a](https://github.com/S-O-O-P/S-O-O-P-React/assets/73331620/12570e10-d02f-4e91-875a-f60b66fe06a0)

### 해결
![footer_a_code_modified](https://github.com/S-O-O-P/S-O-O-P-React/assets/73331620/83ebf196-aa80-44ea-a5b6-baf4fcb531bb)

- [x] FOOTER > Footer.css - a태그 단독 사용 및 적용으로 인한 에러
![footer_a_css](https://github.com/S-O-O-P/S-O-O-P-React/assets/73331620/6de15e9a-464c-4dec-998e-e609092549e2)

### 해결
![footer_a_css_modifed](https://github.com/S-O-O-P/S-O-O-P-React/assets/73331620/0bc0eb6e-391d-47e8-bd41-fe8bab017ab8)

- [x] FOOTER > Footer.css - Footer 영역 재설정
### 재설정 전
![footer_align_error](https://github.com/S-O-O-P/S-O-O-P-React/assets/73331620/a481ffa1-158a-40ee-86c5-2bcd63054242)

### 재설정 후
![footer_align_error_modified](https://github.com/S-O-O-P/S-O-O-P-React/assets/73331620/95bad60b-a704-4c03-ba91-f142d223558f)

### 수정 전
![footer_align_error_css](https://github.com/S-O-O-P/S-O-O-P-React/assets/73331620/47d791b5-0ed2-4a17-9db5-848775acf801)

### 수정 후
![footer_align_error_css_modified](https://github.com/S-O-O-P/S-O-O-P-React/assets/73331620/ed568e8e-af60-4f6e-a3a6-1ff6c03090bc)
![footer_align_error_css_modified2](https://github.com/S-O-O-P/S-O-O-P-React/assets/73331620/8176d5a7-0ede-47cd-84b1-7b40b8b5519a)

- [x] FOOTER > class 사용 에러
### className을 사용하지 않아 발생하는 에러
![footer_class_error_code](https://github.com/S-O-O-P/S-O-O-P-React/assets/73331620/80ba7897-dfd0-4f08-978c-93ea15437595)

### class를 className으로 변경
![footer_class_error_code](https://github.com/S-O-O-P/S-O-O-P-React/assets/73331620/aefa8c54-7afc-4d80-a5ed-301014b7983e)
ading footer_class_error.PNG…]()

## HEADER 
- [x] 메뉴 hover시, 동적 효과 추가
- [x] box-shadow 효과 수정
![header_modifed](https://github.com/S-O-O-P/S-O-O-P-React/assets/73331620/cb489cce-c6cf-4679-b1ab-56802b0c5909)
![header_modifed2](https://github.com/S-O-O-P/S-O-O-P-React/assets/73331620/348fe060-df0c-45c9-9ffd-a9d0ac757d2f)

**Comment by neogoolboss** [comment]
고생하셨습니다

**Comment by Bini0104** [comment]
확인했습니다!👍

**Comment by LEEMINKUK** [comment]
제가 구현한 부분 에러 였네요. 
죄송합니다.
해결해 주셔서 감사합니다.
