### ISSUE TITLE
[FEATURE][CULTUREINFO][API] 공연/전시 공공데이터 API 호출 및 적용 작업

### ISSUE THREAD

**Issue by shubiduba1212** [S-O-O-P/S-O-O-P-React#59]
## 💼 어떤 기능인가요?
 [FEATURE][CULTUREINFO][API] 공연/전시 공공데이터 API 호출 및 적용 작업입니다.

## ✅ 작업 상세 내용
- [x] 공공데이터 API 호출
- [x] 호출한 데이터 JSON형태로 변환
- [x] JSON으로 변환한 데이터 [FEATURE][MAIN] 메인 페이지 적용
- [x] JSON으로 변환한 데이터 [FEATURE][CULTUREINFO][MAIN] 공연/전시 정보 페이지 적용
- [x] JSON으로 변환한 데이터 [FEATURE][CULTUREINFO][DETAIL] 공연/전시 상세 페이지 적용 
- [x] JSON으로 변환한 데이터 타 도메인에 전달하는 작업

**Comment by shubiduba1212** [comment]
### [24.06.27 Access error ]
### API 호출시, 콘솔 에러 발생
### 콘솔 에러 내용
![image](https://github.com/S-O-O-P/S-O-O-P-React/assets/73331620/4ff0383d-30fc-4c7e-8cc3-7f0e8f2b05c2)

### 에러 
발생한 오류는 CORS(Cross-Origin Resource Sharing) 정책 제한과 관련된 것으로, CORS는 웹 브라우저에서 한 도메인(origin)에서 다른 도메인의 자원에 접근하는 것을 제한하는 보안 기능이다.
이 오류는 API 서버(http://www.culture.go.kr)가 응답에 필요한 CORS 헤더(Access-Control-Allow-Origin)를 포함하지 않기 때문에 발생한다. React 애플리케이션이 http://localhost:3000에서 이 API로부터 데이터를 가져오려고 할 때, 브라우저가 보안 정책에 따라 요청을 차단한다.

### 해결방안
서버 측 프록시를 사용하는 것이 CORS 문제를 해결하는 권장 방법이다. 이 방법은 보안을 유지하면서 React 애플리케이션이 CORS 헤더를 지원하지 않는 외부 API에 데이터에 접근할 수 있도록 한다.
![image](https://github.com/S-O-O-P/S-O-O-P-React/assets/73331620/0e796531-fe14-4999-93d4-bf7be00bee98)

[출처: ChatGPT]

**Comment by neogoolboss** [comment]
![image](https://github.com/S-O-O-P/S-O-O-P-React/assets/157683242/dccce064-a98c-46f2-8ce5-afe10094d5f5)
덕분에 잘잘 쓰고있습니다 🦝👍
