### ISSUE TITLE
[FEATURE][MAIN] HEADER 색상 적용 CSS&JS에러

### ISSUE THREAD

**Issue by shubiduba1212** [S-O-O-P/S-O-O-P-React#60]
##  💼 어떤 기능인가요?
[FEATURE][MAIN] 메인페이지 진입시, HEADER 색상이 메인 컬러가 아닌 흰색으로 적용되어있으며, 타 페이지에도 영향을 주고 있는 것으로 확인된 CSS&JS 적용 에러입니다.
![image](https://github.com/S-O-O-P/S-O-O-P-React/assets/73331620/99689c95-218d-42d9-a014-d13a70a2590a)

## ✅ 작업 상세 내용
- [ ] 메인 페이지 진입시 + App.js 실행시, 메인 컬러 header로 적용
- [ ] 메인 페이지 이외의 페이지에서는 흰색 header로 적용

## 🐝 예상 결과

> 예상했던 정상적인 결과가 어떤 것이었는지 설명해주세요
### 메인 페이지 진입시 header
![image](https://github.com/S-O-O-P/S-O-O-P-React/assets/73331620/58fe49a6-7bad-4ebe-944d-b99724953008)

**Comment by neogoolboss** [comment]
믿습니다!
