### ISSUE TITLE
[FEATUER][HEADER] 메인 → 다른 페이지 이동 헤더 로고 사라짐 에러

### ISSUE THREAD

**Issue by Bini0104** [S-O-O-P/S-O-O-P-React#64]
### 이미지를 클릭해서 들어가면 헤더 로고가 사라집니다.(새로고침하면 생김)

![image](https://github.com/S-O-O-P/S-O-O-P-React/assets/157683303/87d59dd5-5388-4230-90ac-86e2d46991a7)

![image](https://github.com/S-O-O-P/S-O-O-P-React/assets/157683303/caddadb1-d18f-4ffc-b3d2-945d6832e126)

**Comment by shubiduba1212** [comment]
bug 리포트 감사해요! 빠른 수정 진행하겠습니다!😅

**Comment by shubiduba1212** [comment]
### [해결방법] Main.js 코드 수정
![image](https://github.com/S-O-O-P/S-O-O-P-React/assets/73331620/0810ba68-c037-46a7-b1ef-595570795b25)

### [View] 코드 수정 후, 메인페이지에서 공연/상세정보 페이지로 이동시
![image](https://github.com/S-O-O-P/S-O-O-P-React/assets/73331620/78da6a31-f11a-4fc2-9b09-77f1177d6e40)

메인페이지에서 언마운트될시, 정적 리소스 경로로 다시 설정해줘야하는데, 상대경로로 설정해서 이미지가 나오지 않는 에러가 발생했습니다.  
Main.js에서 언마운트 할 시에 위 코드 내용으로 수정하니 메인페이지에서 이동해도 depth 영향 없이, 정상적으로 로고 표시됩니다.
