### ISSUE TITLE
[FEATURE][HONEYPOT][DETAIL] FRONT

### ISSUE THREAD

**Issue by neogoolboss** [S-O-O-P/S-O-O-P-React#69]
## 💼 어떤 기능인가요?
> [FEATURE][HONEYPOT][DETAIL]

## ✅ 작업 상세 내용
- [x] 로그인한 유저 프로필 정보 받아오기(더미데이터로 테스트)
- [x] 등록한 데이터 연결
- [x] 작성자 / 참여자 VIEW 구현
- [x] 추천 허니팟 구현
- [x] 댓글 구현(조회/등록/수정/삭제)
- [x] 참여여부 승인/미승인 기능까지 구현
- [x] 게시글 삭제기능 (호스트)
- [x] 게시글 신고기능 (참여자)

**Comment by shubiduba1212** [comment]
작업 많이 진행하셨네요😆 저도 빠르게×빠르게 진행해보겠습니다!

**Comment by neogoolboss** [comment]
댓글 CRUD 완료
